### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by tin2tin** [britalmeida/blender_addon_push_to_talk#1]
Any hints on how to get this great thing working on Windows? Or is it downright impossible?

**Comment by britalmeida** [comment]
Hello!

Currently I have _no plans_ to get the add-on working on Windows, as I'm doing this in my spare time.
Even on Linux, so far, I've tested it only on my personal laptop. It might not work with a different setup.

If you are willing to try and find out how to do the sound recording on Windows, I can integrate that with the add-on UI today after work (in ~10h).
You could start by searching how to record sound in the command line with ffmpeg, or maybe there is a "Windows way" to do it, without needing to install ffmpeg.

If you'd just like to use the add-on asap and don't have Linux, you could try copying a Linux live distro to a USB stick and use it to run Blender.

**Comment by tin2tin** [comment]
I've reached out the the coder of the Blender-included-audio-lib: https://github.com/neXyon/audaspace/issues/30
