### ISSUE TITLE
Recording Lag

### ISSUE THREAD

**Issue by enzyme69** [britalmeida/blender_addon_push_to_talk#10]
I noticed in recent Blender 2.92 that recording has "lag". Sometimes the recording only started few frames after recording already running, so the audio being cut incorrectly.

If I do multiple recording with frame running, I can also see gap.

**Comment by britalmeida** [comment]
Hello! We've had another report where we discussed latency issues: #4. Unfortunately, we haven't reached a conclusion.
In that report, there are some details about flags that you could try passing to ffmpeg by pasting them in this add-on's code and see if it solves your problem?

**Comment by RobinsonVal** [comment]
i get an error message when I hit the record button and the record button will not turn off after that also there is no recording. something about no "self start line" line 344 line 320 line 1420

**Comment by RobinsonVal** [comment]
i get an error message when I hit the record button and the record button will not turn off after that also there is no recording. something about no "self start line" line 344 line 320 line 1420

**Comment by britalmeida** [comment]
I believe that this issue has been fixed by @DarkDefender in bd1e9486ffd104441e9d7dda5f297220d2c239b1
