### ISSUE TITLE
Could not record due to not finding the recording folder 

### ISSUE THREAD

**Issue by razzysilver** [britalmeida/blender_addon_push_to_talk#12]
even after naming a recording folder it does not record 

![image](https://user-images.githubusercontent.com/99765116/154156494-fb31ea38-f3af-45c9-80d5-c533160fddb5.png)

**Comment by britalmeida** [comment]
Hi @razzysilver , sorry for the long time replying, I didn't notice this one.
Is it still a problem for you?

What is the folder name you are giving? You're selecting it via Blender's file browser or pasting a path?

**Comment by RXRAY3D** [comment]
Hello, I also have the same problem. I've been trying it from blender 3.4, 3.3, 3.0.1, 2.93.7, and I get the same error and can't find the sound device.
![imagen_2023-03-13_172526895](https://user-images.githubusercontent.com/74636026/224846328-03672b47-1316-4802-8c5a-41825b699dad.png)
![imagen_2023-03-13_172537009](https://user-images.githubusercontent.com/74636026/224846350-eab301a6-077e-4800-b768-79870ba77e67.png)

**Comment by britalmeida** [comment]
I could reproduce and I've fixed the issue. 🎉 
It would happen on Windows, when ffmpeg was not installed and incorrectly report it as bad folder name for soundclips. Error reporting is now improved.
