### ISSUE TITLE
Can't find the sound card on any version of blender from 2.8 to 3.5

### ISSUE THREAD

**Issue by kebab03** [britalmeida/blender_addon_push_to_talk#13]

**Comment by britalmeida** [comment]
Hello @kebab03 
This add-on was developed for Blender 2.83 and should work well up to the versions in development now (3.3 and 3.4).
What makes you say it is a version problem?

**Comment by britalmeida** [comment]
Hello @kebab03 
This add-on was developed for Blender 2.83 and should work well up to the versions in development now (3.3 and 3.4).
What makes you say it is a version problem?
Can you provide details on what you see, your setup (OS, sound cards) and any possible errors shown in the console?

**Comment by kebab03** [comment]
Unfortunately  ,in  photo 📸  you can see that, can't choose any sound source.
<img width="960" alt="2022-07-31 18_02_05-Greenshot" src="https://user-images.githubusercontent.com/68882205/182037453-2028dff1-b3b7-4772-bc1b-8d3c0dce9e14.png">

**Comment by fsiddi** [comment]
Can you show the output of the console? https://docs.blender.org/manual/en/3.2/advanced/command_line/launch/windows.html?#details 

There might be some hint there.

**Comment by kebab03** [comment]
after opening Blender from the cmd in the Bleder folder i get the following , although the recoder show that it's recording but no audio file is generated at the end of the recording and in the sound card i have no options.as you can see in the attached photo .Thank you in advance .

C:\Program Files\Blender Foundation\Blender 2.83>blender.exe
Read prefs: C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.83\2.83\python
WARN (bpy.rna): C:\Users\blender\git\blender-v283\blender.git\source\blender\python\intern\bpy_rna.c:1479 pyrna_enum_to_py: current value '0' matches no enum in 'SEQUENCER_PushToTalk_Preferences', '(null)', 'audio_input_device'
Registered Animation Nodes

**Comment by fsiddi** [comment]
Can you confirm that you have ffmpeg installed on your system? What happens if you type:

```
ffmpeg -list_devices true -f dshow -i dummy 
```
in your cmd?

**Comment by kebab03** [comment]
i get the following:

C:\Users\user>ffmpeg -list_devices true -f dshow -i dummy
ffmpeg version N-107249-g9dfec90253-20220626 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220626
  libavutil      57. 27.100 / 57. 27.100
  libavcodec     59. 34.100 / 59. 34.100
  libavformat    59. 25.100 / 59. 25.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 41.100 /  8. 41.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[dshow @ 0000027611c32840] "Iriun Webcam" (video)
[dshow @ 0000027611c32840]   Alternative name "@device_pnp_\\?\root#camera#0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\{2a1f7d28-c666-4848-a04c-3b1a9f2546a2}"
[dshow @ 0000027611c32840] "HD User Facing" (video)
[dshow @ 0000027611c32840]   Alternative name "@device_pnp_\\?\usb#vid_04f2&pid_b64f&mi_00#6&147b4c&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global"
[dshow @ 0000027611c32840] "OBS Virtual Camera" (video)
[dshow @ 0000027611c32840]   Alternative name "@device_sw_{860BB310-5D01-11D0-BD3B-00A0C911CE86}\{A3FCE0F5-3493-419F-958A-ABA1250EC20B}"
[dshow @ 0000027611c32840] "Microphone Array (Realtek(R) Audio)" (audio)
[dshow @ 0000027611c32840]   Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{9917293A-ABC1-4579-BD29-1D8DFD10F220}"
[dshow @ 0000027611c32840] "Microfono (Iriun Webcam)" (audio)
[dshow @ 0000027611c32840]   Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{8A14DDD1-EDDA-4B5F-99C6-64F3F0982499}"
dummy: Immediate exit requested

**Comment by fsiddi** [comment]
It looks like the output parser can't handle the output of FFMPEG. https://github.com/britalmeida/push_to_talk/blob/master/__init__.py#L113

Perhaps the output format changed with a new FFMPEG release. It would be helpful if you could install an earlier version (try v4 https://ffmpeg.org/download.html#build-windows) and let us know if that has a different output.

**Comment by kebab03** [comment]
HI, thank you for your suggestion,it did work with the ffMPEG  version 4.3,  but the drawback  is the sound quality  compare with the Windows built in Softwaren Xbox Game bar . Can you tell how can i get the high quality of sound 🔊?Thank you in any way .Have a good day .

**Comment by fsiddi** [comment]
Hi, I think the best would be to try and upgrade to FFmpeg 5. I suggest to close this for now, as we found what causes the issue, and will put an FFmpeg upgrade on the roadmap. Unfortunately I can't foresee when the upgrade will happen, as time is scarce. Thank you for helping on this by patiently testing things out!
