### ISSUE TITLE
Push to Talk not Finding Mic

### ISSUE THREAD

**Issue by gkorman555** [britalmeida/blender_addon_push_to_talk#14]
Hi, I've installed the add on to Blender 3.3.  I can't select my mic from the drop down in the configuration in the video editor.  Please advise on what configuration I'm missing.

Thank you

**Comment by aputit** [comment]
hello i have same problem any advice

**Comment by hced** [comment]
Here's not even finding a Sound Card (which is properly installed and works elsewhere, etc). Windows 11 22H2 / Blender 3.4.0.

The Sound Card menu is empty.

**Comment by Yebihashu** [comment]
Same for me.
No options are shown to chose in the Sound Card drop down.

**Comment by mattcastley** [comment]
I have the same issue.

**Comment by britalmeida** [comment]
I believe I've fixed the issue, if not please re-open.
This could happen when ffmpeg was not installed or had a different format to output sound devices than anticipated. More formats are now supported on Windows and error reporting is also improved.
