### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by phil123456** [britalmeida/blender_addon_push_to_talk#19]
link to ffmpeg instructions lead to a site were download links are broken

**Comment by britalmeida** [comment]
@phil123456 indeed, it looks that way. Thank you for reporting.
Can you try downloading with this link? https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z

It's one that is linked in the [official ffmpeg website](https://ffmpeg.org/download.html#build-windows), but that one doesn't have instructions, just the links.

@phil123456 if you've just figured out how to install it, do you have instructions to recommend?
Maybe one of these?
https://www.wikihow.com/Install-FFmpeg-on-Windows
https://www.geeksforgeeks.org/how-to-install-ffmpeg-on-windows/

@tin2tin could you report the issue to Greg Zaal? It looks like he hasn't updated his website blogpost in a while.

**Comment by britalmeida** [comment]
Fixed with 8e6d1c7
