### ISSUE TITLE
Link to the FFMPEG Windows installation leads to faulty download links

### ISSUE THREAD

**Issue by thelazyone** [britalmeida/blender_addon_push_to_talk#20]
I'm aware that this is not directly an issue of the repo, but the link you provided does link to https://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/ , which then provides download links on https://ffmpeg.zeranoe.com/builds/ , which appear to be currently unreachable. 

Pointing to a different guide on how to install FFMPEG on windows could be recommended.

**Comment by britalmeida** [comment]
@thelazyone thank you for reporting!
This issue got mentioned yesterday in #19. I'm updating the README with one of the links I've mentioned in #19, but please feel free to suggest better instructions if you've just went thought the process yourself :)

**Comment by britalmeida** [comment]
Fixed with 8e6d1c7
