### ISSUE TITLE
ffmpeg path/alert

### ISSUE THREAD

**Issue by tin2tin** [britalmeida/blender_addon_push_to_talk#8]
If this add-on is included in Blender, maybe it would be a nice gesture to users to include what pullusb suggests here(manual entry of ffmpeg path & and an alert if no ffmpeg found anywhere): https://github.com/britalmeida/push_to_talk/pull/3#commitcomment-40586372

**Comment by britalmeida** [comment]
For this add-on to be official, it would need to use the ffmpeg bundled with Blender, as users can't be asked to install additional dependencies.
This add-on is a proof concept. To be made proper it would need a more robust recording solution (maybe from Audaspace), and less hacky way of showing visual feedback (I'm adding a temporary color strip).

I currently don't have plans of implementing this functionality (or support for it) directly in Blender.

**Comment by tin2tin** [comment]
Ok,I thought it was included in Blender because of the bug-report on phabricator. My bad.
