### ISSUE TITLE
macOS, Blender 2.92 official - no ffmpeg, no soundcard list

### ISSUE THREAD

**Issue by enzyme69** [britalmeida/blender_addon_push_to_talk#9]
With Blender 2.92 official and pushtotalk addon, somewhat I cannot do the recording, as it could not seem to find soundcard or access to ffmpeg library. Maybe something need to be setup manually by user or maybe addon has bug?

<img width="819" alt="Screen Shot 2021-02-27 at 8 47 27 am" src="https://user-images.githubusercontent.com/3952687/109358822-7bc96f80-78d8-11eb-8b01-b9baf64ac355.png">

**Comment by britalmeida** [comment]
Hello!
I confirmed this add-on to be working on the 2.92 official release and on the 2.93 development build too.

From the error it looks like ffmpeg is not installed? (Sorry, it isn't a nice and clear error message)

**Comment by enzyme69** [comment]
Hmm... I don't know why I am sure I have ffmpeg (how to test?)

I cannot see soundcard in 2.93:

<img width="469" alt="Screen Shot 2021-03-26 at 10 04 40 am" src="https://user-images.githubusercontent.com/3952687/112554636-c62c0680-8e1a-11eb-85a9-11c620840c4d.png">

**Comment by enzyme69** [comment]
The problem might be on my end, when I run ffmpeg, terminal crashes. Anyways I will get that fixed first.

**Comment by enzyme69** [comment]
Somehow if I run Blender via Terminal, the add-on can find FFmpeg.
